### PR TITLE
Control rod length changed

### PR DESCRIPTION
**Pull request by andrewryh**
Closes issue #5

### CODE REVIEW

**Comment by dogrady2** [comment]
Looks good. Should we go ahead and change structure of this repo while we are at it?

**Comment by andrewryh** [comment]
> Looks good. Should we go ahead and change structure of this repo while we are at it?

One Issue - One PR - One problem :)

**Review by dogrady2 — APPROVED** [review]

**Review by dogrady2 — COMMENTED** [review]
These were taken taken from the MSRE example with moltres. I will need to change them there also.

**Comment by andrewryh** [comment]
> These were taken taken from the MSRE example with moltres. I will need to change them there also.

Ok

**Pull request merged**
